name: Checkpoint 2
on:
  pull_request: [main]
  schedule:
    - cron: '0 2 * * *'
jobs:
  run-checkpoint-2:
    runs-on: ubuntu-latest
    steps:
       - name: Check out repository
         uses: actions/checkout@v7
       - run: echo "Triggered by ${{ github.event_name }}"